### PR TITLE
use nrepl, not eval

### PR DESCRIPTION
**Pull request by pdenno**
As the subject suggests, this is a major change. Writing a reliable REPL, which is where this code seemed to be heading, is a lot of work. tools.nrepl is a REPL solution made just for this sort of problem, and it is tested (used by emacs/cider etc.) and solid. See the section [why nREPL?](https://github.com/clojure/tools.nrepl) at tools.nrepl github.

I have not experienced any problems changing namespaces in this fork. I implemented stacktraces using code from cider-nrepl.

### CODE REVIEW

**Comment by pdenno** [comment]
I apparently still don't quite understand how squashing commits works. Thus the 3 commits...Sorry.

**Comment by roryk** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by roryk** [comment]
Thank you so so so so so so so much, Peter. This is incredible. I am so happy, it would have taken me forever to figure that out. I gave you push access to the repository, as far as I am concerned you should own it.

**Comment by pdenno** [comment]
Well thanks for all the work on Zero MQ and the interface with the the 
notebook! That would have taken me ages to figure out, and I probably 
wouldn't have taken on the work had I not seen something "close enough" 
to usable in clojupyter.

**Comment by roryk** [comment]
Sweet, I have been walking around happy today. These bugs were weighing on me and I didn't realize it. Thanks so much!

**Comment by thomasjm** [comment]
@pdenno , it seems this PR actually broke something basic: you can no longer print to stdout. I.e. something like `(prn "HI")` doesn't show any output other than the `nil` result.

I think the reason is that stdout used to be captured by the `(binding [*out* s#] ...)` currently at `core.clj:282`, back when this kernel worked using `eval`. 

In the world of `nrepl-eval`, I'm not sure how stdout capturing should work. Any chance you know how to add it back? :)

**Pull request merged**
